// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32S3-Touch-AMOLED-1.64-Robot_SquareLine_Project

#include "ui.h"

lv_obj_t * uic_BarBR3;
lv_obj_t * uic_BarBR2;
lv_obj_t * uic_BarBR1;
lv_obj_t * uic_BarFR3;
lv_obj_t * uic_BarFR2;
lv_obj_t * uic_BarFR1;
lv_obj_t * uic_BarBL3;
lv_obj_t * uic_BarBL2;
lv_obj_t * uic_BarBL1;
lv_obj_t * uic_BarFL3;
lv_obj_t * uic_BarFL2;
lv_obj_t * uic_BarFL1;
lv_obj_t * uic_CalibrateButton;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ServoLabelsLeft = NULL;
lv_obj_t * ui_CalibrateButton = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ServoLabelsRight = NULL;
lv_obj_t * ui_ContainerCalbrationLeft = NULL;
lv_obj_t * ui_BarFL1 = NULL;
lv_obj_t * ui_BarFL2 = NULL;
lv_obj_t * ui_BarFL3 = NULL;
lv_obj_t * ui_BarBL1 = NULL;
lv_obj_t * ui_BarBL2 = NULL;
lv_obj_t * ui_BarBL3 = NULL;
lv_obj_t * ui_ContainerCalbrationRight = NULL;
lv_obj_t * ui_BarFR1 = NULL;
lv_obj_t * ui_BarFR2 = NULL;
lv_obj_t * ui_BarFR3 = NULL;
lv_obj_t * ui_BarBR1 = NULL;
lv_obj_t * ui_BarBR2 = NULL;
lv_obj_t * ui_BarBR3 = NULL;
lv_obj_t * ui_WiggleButton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_CalibrationInfo = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoLabelsLeft = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ServoLabelsLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServoLabelsLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoLabelsLeft, 15);
    lv_obj_set_y(ui_ServoLabelsLeft, 15);
    lv_label_set_text(ui_ServoLabelsLeft, "FL1\nFL2\nFL3\nBL1\nBL2\nBL3");
    lv_obj_set_style_text_font(ui_ServoLabelsLeft, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrateButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_CalibrateButton, 100);
    lv_obj_set_height(ui_CalibrateButton, 50);
    lv_obj_set_x(ui_CalibrateButton, -80);
    lv_obj_set_y(ui_CalibrateButton, 75);
    lv_obj_set_align(ui_CalibrateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_CalibrateButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Calibrate");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoLabelsRight = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ServoLabelsRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ServoLabelsRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoLabelsRight, 226);
    lv_obj_set_y(ui_ServoLabelsRight, 15);
    lv_label_set_text(ui_ServoLabelsRight, "FR1\nFR2\nFR3\nBR1\nBR2\nBR3");
    lv_obj_set_style_text_font(ui_ServoLabelsRight, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCalbrationLeft = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_ContainerCalbrationLeft);
    lv_obj_set_width(ui_ContainerCalbrationLeft, 142);
    lv_obj_set_height(ui_ContainerCalbrationLeft, 122);
    lv_obj_set_x(ui_ContainerCalbrationLeft, 55);
    lv_obj_set_y(ui_ContainerCalbrationLeft, 17);
    lv_obj_set_flex_flow(ui_ContainerCalbrationLeft, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerCalbrationLeft, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerCalbrationLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerCalbrationLeft, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerCalbrationLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarFL1 = lv_bar_create(ui_ContainerCalbrationLeft);
    lv_bar_set_mode(ui_BarFL1, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarFL1, 0, 1024);
    lv_obj_set_width(ui_BarFL1, 140);
    lv_obj_set_height(ui_BarFL1, 14);
    lv_obj_set_x(ui_BarFL1, 59);
    lv_obj_set_y(ui_BarFL1, 18);
    lv_obj_set_align(ui_BarFL1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarFL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarFL1, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarFL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarFL1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarFL1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarFL1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarFL1, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarFL1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarFL2 = lv_bar_create(ui_ContainerCalbrationLeft);
    lv_bar_set_mode(ui_BarFL2, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarFL2, 0, 1024);
    lv_obj_set_width(ui_BarFL2, 140);
    lv_obj_set_height(ui_BarFL2, 14);
    lv_obj_set_x(ui_BarFL2, 59);
    lv_obj_set_y(ui_BarFL2, 40);
    lv_obj_set_style_radius(ui_BarFL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarFL2, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarFL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarFL2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarFL2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarFL2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarFL2, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarFL2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarFL3 = lv_bar_create(ui_ContainerCalbrationLeft);
    lv_bar_set_mode(ui_BarFL3, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarFL3, 0, 1024);
    lv_obj_set_width(ui_BarFL3, 140);
    lv_obj_set_height(ui_BarFL3, 14);
    lv_obj_set_x(ui_BarFL3, 59);
    lv_obj_set_y(ui_BarFL3, 40);
    lv_obj_set_style_radius(ui_BarFL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarFL3, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarFL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarFL3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarFL3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarFL3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarFL3, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarFL3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBL1 = lv_bar_create(ui_ContainerCalbrationLeft);
    lv_bar_set_mode(ui_BarBL1, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarBL1, 0, 1024);
    lv_obj_set_width(ui_BarBL1, 140);
    lv_obj_set_height(ui_BarBL1, 14);
    lv_obj_set_x(ui_BarBL1, 59);
    lv_obj_set_y(ui_BarBL1, 40);
    lv_obj_set_style_radius(ui_BarBL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarBL1, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarBL1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarBL1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBL1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBL1, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBL1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBL2 = lv_bar_create(ui_ContainerCalbrationLeft);
    lv_bar_set_mode(ui_BarBL2, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarBL2, 0, 1024);
    lv_obj_set_width(ui_BarBL2, 140);
    lv_obj_set_height(ui_BarBL2, 14);
    lv_obj_set_x(ui_BarBL2, 59);
    lv_obj_set_y(ui_BarBL2, 40);
    lv_obj_set_style_radius(ui_BarBL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarBL2, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarBL2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarBL2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBL2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBL2, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBL2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBL3 = lv_bar_create(ui_ContainerCalbrationLeft);
    lv_bar_set_mode(ui_BarBL3, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarBL3, 0, 1024);
    lv_obj_set_width(ui_BarBL3, 140);
    lv_obj_set_height(ui_BarBL3, 14);
    lv_obj_set_x(ui_BarBL3, 59);
    lv_obj_set_y(ui_BarBL3, 40);
    lv_obj_set_style_radius(ui_BarBL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarBL3, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarBL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarBL3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarBL3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBL3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBL3, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBL3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerCalbrationRight = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_ContainerCalbrationRight);
    lv_obj_set_width(ui_ContainerCalbrationRight, 142);
    lv_obj_set_height(ui_ContainerCalbrationRight, 122);
    lv_obj_set_x(ui_ContainerCalbrationRight, 270);
    lv_obj_set_y(ui_ContainerCalbrationRight, 17);
    lv_obj_set_flex_flow(ui_ContainerCalbrationRight, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerCalbrationRight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerCalbrationRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerCalbrationRight, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerCalbrationRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarFR1 = lv_bar_create(ui_ContainerCalbrationRight);
    lv_bar_set_mode(ui_BarFR1, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarFR1, 0, 1024);
    lv_obj_set_width(ui_BarFR1, 140);
    lv_obj_set_height(ui_BarFR1, 14);
    lv_obj_set_x(ui_BarFR1, 59);
    lv_obj_set_y(ui_BarFR1, 18);
    lv_obj_set_style_radius(ui_BarFR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarFR1, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarFR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarFR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarFR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarFR1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarFR1, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarFR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarFR2 = lv_bar_create(ui_ContainerCalbrationRight);
    lv_bar_set_mode(ui_BarFR2, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarFR2, 0, 1024);
    lv_obj_set_width(ui_BarFR2, 140);
    lv_obj_set_height(ui_BarFR2, 14);
    lv_obj_set_x(ui_BarFR2, 59);
    lv_obj_set_y(ui_BarFR2, 40);
    lv_obj_set_style_radius(ui_BarFR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarFR2, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarFR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarFR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarFR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarFR2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarFR2, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarFR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarFR3 = lv_bar_create(ui_ContainerCalbrationRight);
    lv_bar_set_mode(ui_BarFR3, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarFR3, 0, 1024);
    lv_obj_set_width(ui_BarFR3, 140);
    lv_obj_set_height(ui_BarFR3, 14);
    lv_obj_set_x(ui_BarFR3, 59);
    lv_obj_set_y(ui_BarFR3, 40);
    lv_obj_set_style_radius(ui_BarFR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarFR3, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarFR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarFR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarFR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarFR3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarFR3, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarFR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBR1 = lv_bar_create(ui_ContainerCalbrationRight);
    lv_bar_set_mode(ui_BarBR1, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarBR1, 0, 1024);
    lv_obj_set_width(ui_BarBR1, 140);
    lv_obj_set_height(ui_BarBR1, 14);
    lv_obj_set_x(ui_BarBR1, 59);
    lv_obj_set_y(ui_BarBR1, 40);
    lv_obj_set_style_radius(ui_BarBR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarBR1, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarBR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarBR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarBR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBR1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBR1, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBR2 = lv_bar_create(ui_ContainerCalbrationRight);
    lv_bar_set_mode(ui_BarBR2, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarBR2, 0, 1024);
    lv_obj_set_width(ui_BarBR2, 140);
    lv_obj_set_height(ui_BarBR2, 14);
    lv_obj_set_x(ui_BarBR2, 59);
    lv_obj_set_y(ui_BarBR2, 40);
    lv_obj_set_style_radius(ui_BarBR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarBR2, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarBR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarBR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarBR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBR2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBR2, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBR3 = lv_bar_create(ui_ContainerCalbrationRight);
    lv_bar_set_mode(ui_BarBR3, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarBR3, 0, 1024);
    lv_obj_set_width(ui_BarBR3, 140);
    lv_obj_set_height(ui_BarBR3, 14);
    lv_obj_set_x(ui_BarBR3, 59);
    lv_obj_set_y(ui_BarBR3, 40);
    lv_obj_set_style_radius(ui_BarBR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarBR3, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarBR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarBR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarBR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarBR3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarBR3, lv_color_hex(0x5E87EE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WiggleButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_WiggleButton, 100);
    lv_obj_set_height(ui_WiggleButton, 50);
    lv_obj_set_x(ui_WiggleButton, 80);
    lv_obj_set_y(ui_WiggleButton, 75);
    lv_obj_set_align(ui_WiggleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiggleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiggleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_WiggleButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Wiggle");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationInfo = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_CalibrationInfo, 400);
    lv_obj_set_height(ui_CalibrationInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationInfo, 0);
    lv_obj_set_y(ui_CalibrationInfo, 35);
    lv_obj_set_align(ui_CalibrationInfo, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_CalibrationInfo, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_CalibrateButton = ui_CalibrateButton;
    uic_BarFL1 = ui_BarFL1;
    uic_BarFL2 = ui_BarFL2;
    uic_BarFL3 = ui_BarFL3;
    uic_BarBL1 = ui_BarBL1;
    uic_BarBL2 = ui_BarBL2;
    uic_BarBL3 = ui_BarBL3;
    uic_BarFR1 = ui_BarFR1;
    uic_BarFR2 = ui_BarFR2;
    uic_BarFR3 = ui_BarFR3;
    uic_BarBR1 = ui_BarBR1;
    uic_BarBR2 = ui_BarBR2;
    uic_BarBR3 = ui_BarBR3;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ServoLabelsLeft = NULL;
    uic_CalibrateButton = NULL;
    ui_CalibrateButton = NULL;
    ui_Label2 = NULL;
    ui_ServoLabelsRight = NULL;
    ui_ContainerCalbrationLeft = NULL;
    uic_BarFL1 = NULL;
    ui_BarFL1 = NULL;
    uic_BarFL2 = NULL;
    ui_BarFL2 = NULL;
    uic_BarFL3 = NULL;
    ui_BarFL3 = NULL;
    uic_BarBL1 = NULL;
    ui_BarBL1 = NULL;
    uic_BarBL2 = NULL;
    ui_BarBL2 = NULL;
    uic_BarBL3 = NULL;
    ui_BarBL3 = NULL;
    ui_ContainerCalbrationRight = NULL;
    uic_BarFR1 = NULL;
    ui_BarFR1 = NULL;
    uic_BarFR2 = NULL;
    ui_BarFR2 = NULL;
    uic_BarFR3 = NULL;
    ui_BarFR3 = NULL;
    uic_BarBR1 = NULL;
    ui_BarBR1 = NULL;
    uic_BarBR2 = NULL;
    ui_BarBR2 = NULL;
    uic_BarBR3 = NULL;
    ui_BarBR3 = NULL;
    ui_WiggleButton = NULL;
    ui_Label1 = NULL;
    ui_CalibrationInfo = NULL;

}
