// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32S3-Touch-AMOLED-1.64-Robot_SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_ContainerServoInfoLeft;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TempFL1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_TempFL2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_TempFL3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TempBL1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_TempBL2;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TempBL3;
extern lv_obj_t * ui_ContainerServoInfoRight;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_TempFR1;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TempFR2;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_TempFR3;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_TempBR1;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_TempBR2;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_TempBR3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

