// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32S3-Touch-AMOLED-1.64-Robot_SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_BatteryStatusLabel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_BatteryIcon;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_WifiIcon;
extern lv_obj_t * ui_WifiAPLabel;
extern lv_obj_t * ui_WifiStatusLabel;
extern lv_obj_t * ui_ConnectedIcon;
extern lv_obj_t * ui_VoltageCurrentLabel;
extern lv_obj_t * ui_ServoStatusContainer;
extern lv_obj_t * ui_ServoStatusFL1;
extern lv_obj_t * ui_ServoStatusFL2;
extern lv_obj_t * ui_ServoStatusFL3;
extern lv_obj_t * ui_ServoStatusFR1;
extern lv_obj_t * ui_ServoStatusFR2;
extern lv_obj_t * ui_ServoStatusFR3;
extern lv_obj_t * ui_ServoStatusBL1;
extern lv_obj_t * ui_ServoStatusBL2;
extern lv_obj_t * ui_ServoStatusBL3;
extern lv_obj_t * ui_ServoStatusBR1;
extern lv_obj_t * ui_ServoStatusBR2;
extern lv_obj_t * ui_ServoStatusBR3;
extern lv_obj_t * ui_Uptime;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ConnectedIcon;
extern lv_obj_t * uic_ServoStatusContainer;
extern lv_obj_t * uic_ServoStatusFL1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

