// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32S3-Touch-AMOLED-1.64-Robot_SquareLine_Project

#include "ui.h"

lv_obj_t * uic_ServoStatusFL1;
lv_obj_t * uic_ServoStatusContainer;
lv_obj_t * uic_ConnectedIcon;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_BatteryStatusLabel = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_BatteryIcon = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_WifiIcon = NULL;
lv_obj_t * ui_WifiAPLabel = NULL;
lv_obj_t * ui_WifiStatusLabel = NULL;
lv_obj_t * ui_ConnectedIcon = NULL;
lv_obj_t * ui_VoltageCurrentLabel = NULL;
lv_obj_t * ui_ServoStatusContainer = NULL;
lv_obj_t * ui_ServoStatusFL1 = NULL;
lv_obj_t * ui_ServoStatusFL2 = NULL;
lv_obj_t * ui_ServoStatusFL3 = NULL;
lv_obj_t * ui_ServoStatusFR1 = NULL;
lv_obj_t * ui_ServoStatusFR2 = NULL;
lv_obj_t * ui_ServoStatusFR3 = NULL;
lv_obj_t * ui_ServoStatusBL1 = NULL;
lv_obj_t * ui_ServoStatusBL2 = NULL;
lv_obj_t * ui_ServoStatusBL3 = NULL;
lv_obj_t * ui_ServoStatusBR1 = NULL;
lv_obj_t * ui_ServoStatusBR2 = NULL;
lv_obj_t * ui_ServoStatusBR3 = NULL;
lv_obj_t * ui_Uptime = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryStatusLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BatteryStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryStatusLabel, 50);
    lv_obj_set_y(ui_BatteryStatusLabel, 71);
    lv_label_set_text(ui_BatteryStatusLabel, "80%");
    lv_obj_set_style_text_font(ui_BatteryStatusLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 42);
    lv_obj_set_height(ui_Container1, 28);
    lv_obj_set_x(ui_Container1, 7);
    lv_obj_set_y(ui_Container1, 69);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryIcon = lv_img_create(ui_Container1);
    lv_img_set_src(ui_BatteryIcon, &ui_img_battery_sheet_row_png);
    lv_obj_set_width(ui_BatteryIcon, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BatteryIcon, LV_SIZE_CONTENT);    /// 28
    lv_obj_add_flag(ui_BatteryIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatteryIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 32);
    lv_obj_set_height(ui_Container2, 32);
    lv_obj_set_x(ui_Container2, 10);
    lv_obj_set_y(ui_Container2, 6);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiIcon = lv_img_create(ui_Container2);
    lv_img_set_src(ui_WifiIcon, &ui_img_wifi_sheet_32_row_png);
    lv_obj_set_width(ui_WifiIcon, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_WifiIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_add_flag(ui_WifiIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiAPLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WifiAPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiAPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiAPLabel, 50);
    lv_obj_set_y(ui_WifiAPLabel, 2);
    lv_label_set_text(ui_WifiAPLabel, "Router");
    lv_obj_set_style_text_font(ui_WifiAPLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_WifiAPLabel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiStatusLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WifiStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiStatusLabel, 50);
    lv_obj_set_y(ui_WifiStatusLabel, 23);
    lv_label_set_text(ui_WifiStatusLabel, "IP: 192.168.0.1\nWS Clients: 0");
    lv_obj_set_style_text_font(ui_WifiStatusLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectedIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ConnectedIcon, &ui_img_linked_32_png);
    lv_obj_set_width(ui_ConnectedIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ConnectedIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ConnectedIcon, 10);
    lv_obj_set_y(ui_ConnectedIcon, 39);
    lv_obj_add_flag(ui_ConnectedIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ConnectedIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VoltageCurrentLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VoltageCurrentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltageCurrentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltageCurrentLabel, 105);
    lv_obj_set_y(ui_VoltageCurrentLabel, 71);
    lv_label_set_text(ui_VoltageCurrentLabel, "14.5V, 100mA");
    lv_obj_set_style_text_font(ui_VoltageCurrentLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusContainer, 280);
    lv_obj_set_height(ui_ServoStatusContainer, 48);
    lv_obj_set_x(ui_ServoStatusContainer, 0);
    lv_obj_set_y(ui_ServoStatusContainer, 85);
    lv_obj_set_align(ui_ServoStatusContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ServoStatusContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ServoStatusContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServoStatusContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ServoStatusContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ServoStatusContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusFL1 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusFL1, 43);
    lv_obj_set_height(ui_ServoStatusFL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusFL1, 10);
    lv_obj_set_y(ui_ServoStatusFL1, 190);
    lv_label_set_text(ui_ServoStatusFL1, "FL1");
    lv_obj_set_style_text_color(ui_ServoStatusFL1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusFL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusFL1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusFL1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusFL1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusFL1, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusFL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusFL2 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusFL2, 43);
    lv_obj_set_height(ui_ServoStatusFL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusFL2, 48);
    lv_obj_set_y(ui_ServoStatusFL2, 190);
    lv_label_set_text(ui_ServoStatusFL2, "FL2");
    lv_obj_set_style_text_color(ui_ServoStatusFL2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusFL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusFL2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusFL2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusFL2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusFL2, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusFL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusFL3 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusFL3, 43);
    lv_obj_set_height(ui_ServoStatusFL3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusFL3, 86);
    lv_obj_set_y(ui_ServoStatusFL3, 190);
    lv_label_set_text(ui_ServoStatusFL3, "FL3");
    lv_obj_set_style_text_color(ui_ServoStatusFL3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusFL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusFL3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusFL3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusFL3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusFL3, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusFL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusFR1 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusFR1, 43);
    lv_obj_set_height(ui_ServoStatusFR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusFR1, 86);
    lv_obj_set_y(ui_ServoStatusFR1, 190);
    lv_label_set_text(ui_ServoStatusFR1, "FR1");
    lv_obj_set_style_text_color(ui_ServoStatusFR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusFR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusFR1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusFR1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusFR1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusFR1, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusFR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusFR2 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusFR2, 43);
    lv_obj_set_height(ui_ServoStatusFR2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusFR2, 86);
    lv_obj_set_y(ui_ServoStatusFR2, 190);
    lv_label_set_text(ui_ServoStatusFR2, "FR2");
    lv_obj_set_style_text_color(ui_ServoStatusFR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusFR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusFR2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusFR2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusFR2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusFR2, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusFR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusFR3 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusFR3, 43);
    lv_obj_set_height(ui_ServoStatusFR3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusFR3, 86);
    lv_obj_set_y(ui_ServoStatusFR3, 190);
    lv_label_set_text(ui_ServoStatusFR3, "FR3");
    lv_obj_set_style_text_color(ui_ServoStatusFR3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusFR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusFR3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusFR3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusFR3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusFR3, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusFR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusBL1 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusBL1, 43);
    lv_obj_set_height(ui_ServoStatusBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusBL1, 86);
    lv_obj_set_y(ui_ServoStatusBL1, 190);
    lv_label_set_text(ui_ServoStatusBL1, "BL1");
    lv_obj_set_style_text_color(ui_ServoStatusBL1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusBL1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusBL1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusBL1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusBL1, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusBL2 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusBL2, 43);
    lv_obj_set_height(ui_ServoStatusBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusBL2, 86);
    lv_obj_set_y(ui_ServoStatusBL2, 190);
    lv_label_set_text(ui_ServoStatusBL2, "BL2");
    lv_obj_set_style_text_color(ui_ServoStatusBL2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusBL2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusBL2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusBL2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusBL2, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusBL3 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusBL3, 43);
    lv_obj_set_height(ui_ServoStatusBL3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusBL3, 86);
    lv_obj_set_y(ui_ServoStatusBL3, 190);
    lv_label_set_text(ui_ServoStatusBL3, "BL3");
    lv_obj_set_style_text_color(ui_ServoStatusBL3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusBL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusBL3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusBL3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusBL3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusBL3, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusBL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusBR1 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusBR1, 43);
    lv_obj_set_height(ui_ServoStatusBR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusBR1, 86);
    lv_obj_set_y(ui_ServoStatusBR1, 190);
    lv_label_set_text(ui_ServoStatusBR1, "BR1");
    lv_obj_set_style_text_color(ui_ServoStatusBR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusBR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusBR1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusBR1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusBR1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusBR1, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusBR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusBR2 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusBR2, 43);
    lv_obj_set_height(ui_ServoStatusBR2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusBR2, 86);
    lv_obj_set_y(ui_ServoStatusBR2, 190);
    lv_label_set_text(ui_ServoStatusBR2, "BR2");
    lv_obj_set_style_text_color(ui_ServoStatusBR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusBR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusBR2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusBR2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusBR2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusBR2, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusBR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServoStatusBR3 = lv_label_create(ui_ServoStatusContainer);
    lv_obj_set_width(ui_ServoStatusBR3, 43);
    lv_obj_set_height(ui_ServoStatusBR3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ServoStatusBR3, 86);
    lv_obj_set_y(ui_ServoStatusBR3, 190);
    lv_label_set_text(ui_ServoStatusBR3, "BR3");
    lv_obj_set_style_text_color(ui_ServoStatusBR3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ServoStatusBR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ServoStatusBR3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ServoStatusBR3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ServoStatusBR3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServoStatusBR3, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServoStatusBR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Uptime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Uptime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Uptime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Uptime, 10);
    lv_obj_set_y(ui_Uptime, 102);
    lv_label_set_text(ui_Uptime, "Uptime: 0 seconds");
    lv_obj_set_style_text_align(ui_Uptime, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Uptime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ConnectedIcon = ui_ConnectedIcon;
    uic_ServoStatusContainer = ui_ServoStatusContainer;
    uic_ServoStatusFL1 = ui_ServoStatusFL1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_BatteryStatusLabel = NULL;
    ui_Container1 = NULL;
    ui_BatteryIcon = NULL;
    ui_Container2 = NULL;
    ui_WifiIcon = NULL;
    ui_WifiAPLabel = NULL;
    ui_WifiStatusLabel = NULL;
    uic_ConnectedIcon = NULL;
    ui_ConnectedIcon = NULL;
    ui_VoltageCurrentLabel = NULL;
    uic_ServoStatusContainer = NULL;
    ui_ServoStatusContainer = NULL;
    uic_ServoStatusFL1 = NULL;
    ui_ServoStatusFL1 = NULL;
    ui_ServoStatusFL2 = NULL;
    ui_ServoStatusFL3 = NULL;
    ui_ServoStatusFR1 = NULL;
    ui_ServoStatusFR2 = NULL;
    ui_ServoStatusFR3 = NULL;
    ui_ServoStatusBL1 = NULL;
    ui_ServoStatusBL2 = NULL;
    ui_ServoStatusBL3 = NULL;
    ui_ServoStatusBR1 = NULL;
    ui_ServoStatusBR2 = NULL;
    ui_ServoStatusBR3 = NULL;
    ui_Uptime = NULL;

}
