// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32S3-Touch-AMOLED-1.64-Robot_SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_ContainerServoInfoLeft = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TempFL1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_TempFL2 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_TempFL3 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_TempBL1 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_TempBL2 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_TempBL3 = NULL;
lv_obj_t * ui_ContainerServoInfoRight = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_TempFR1 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_TempFR2 = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_TempFR3 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_TempBR1 = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_TempBR2 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_TempBR3 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerServoInfoLeft = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_ContainerServoInfoLeft);
    lv_obj_set_width(ui_ContainerServoInfoLeft, 160);
    lv_obj_set_height(ui_ContainerServoInfoLeft, 170);
    lv_obj_set_x(ui_ContainerServoInfoLeft, 10);
    lv_obj_set_y(ui_ContainerServoInfoLeft, 20);
    lv_obj_set_flex_flow(ui_ContainerServoInfoLeft, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerServoInfoLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerServoInfoLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerServoInfoLeft, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerServoInfoLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_ContainerServoInfoLeft);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 22);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label3, 50);
    lv_obj_set_height(ui_Label3, lv_pct(100));
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label3, "FL1:");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempFL1 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_TempFL1, 50);
    lv_obj_set_height(ui_TempFL1, lv_pct(100));
    lv_obj_set_x(ui_TempFL1, 9);
    lv_obj_set_y(ui_TempFL1, 8);
    lv_obj_set_align(ui_TempFL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempFL1, "24°C");
    lv_obj_set_style_text_align(ui_TempFL1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempFL1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempFL1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempFL1, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempFL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempFL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempFL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempFL1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempFL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_ContainerServoInfoLeft);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 22);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label4, 50);
    lv_obj_set_height(ui_Label4, lv_pct(100));
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "FL2:");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempFL2 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_TempFL2, 50);
    lv_obj_set_height(ui_TempFL2, lv_pct(100));
    lv_obj_set_x(ui_TempFL2, 9);
    lv_obj_set_y(ui_TempFL2, 8);
    lv_obj_set_align(ui_TempFL2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempFL2, "48°C");
    lv_obj_set_style_text_align(ui_TempFL2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempFL2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempFL2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempFL2, lv_color_hex(0xF30202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempFL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempFL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempFL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempFL2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempFL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_ContainerServoInfoLeft);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 22);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label5, 50);
    lv_obj_set_height(ui_Label5, lv_pct(100));
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "FL3:");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempFL3 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_TempFL3, 50);
    lv_obj_set_height(ui_TempFL3, lv_pct(100));
    lv_obj_set_x(ui_TempFL3, 9);
    lv_obj_set_y(ui_TempFL3, 8);
    lv_obj_set_align(ui_TempFL3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempFL3, "37°C");
    lv_obj_set_style_text_align(ui_TempFL3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempFL3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempFL3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempFL3, lv_color_hex(0xF19100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempFL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempFL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempFL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempFL3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempFL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_ContainerServoInfoLeft);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_height(ui_Container6, 22);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label6, 50);
    lv_obj_set_height(ui_Label6, lv_pct(100));
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "BL1:");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBL1 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_TempBL1, 50);
    lv_obj_set_height(ui_TempBL1, lv_pct(100));
    lv_obj_set_x(ui_TempBL1, 9);
    lv_obj_set_y(ui_TempBL1, 8);
    lv_obj_set_align(ui_TempBL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempBL1, "24°C");
    lv_obj_set_style_text_align(ui_TempBL1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempBL1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempBL1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempBL1, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempBL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempBL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempBL1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempBL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_ContainerServoInfoLeft);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 22);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label7, 50);
    lv_obj_set_height(ui_Label7, lv_pct(100));
    lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label7, "BL2:");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBL2 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_TempBL2, 50);
    lv_obj_set_height(ui_TempBL2, lv_pct(100));
    lv_obj_set_x(ui_TempBL2, 9);
    lv_obj_set_y(ui_TempBL2, 8);
    lv_obj_set_align(ui_TempBL2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempBL2, "24°C");
    lv_obj_set_style_text_align(ui_TempBL2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempBL2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempBL2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempBL2, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempBL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempBL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempBL2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempBL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_ContainerServoInfoLeft);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_height(ui_Container8, 22);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label8, 50);
    lv_obj_set_height(ui_Label8, lv_pct(100));
    lv_obj_set_align(ui_Label8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label8, "BL3:");
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBL3 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_TempBL3, 50);
    lv_obj_set_height(ui_TempBL3, lv_pct(100));
    lv_obj_set_x(ui_TempBL3, 9);
    lv_obj_set_y(ui_TempBL3, 8);
    lv_obj_set_align(ui_TempBL3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempBL3, "24°C");
    lv_obj_set_style_text_align(ui_TempBL3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempBL3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempBL3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempBL3, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempBL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempBL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempBL3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempBL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerServoInfoRight = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_ContainerServoInfoRight);
    lv_obj_set_width(ui_ContainerServoInfoRight, 160);
    lv_obj_set_height(ui_ContainerServoInfoRight, 170);
    lv_obj_set_x(ui_ContainerServoInfoRight, 250);
    lv_obj_set_y(ui_ContainerServoInfoRight, 20);
    lv_obj_set_flex_flow(ui_ContainerServoInfoRight, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerServoInfoRight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerServoInfoRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerServoInfoRight, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerServoInfoRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_ContainerServoInfoRight);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_height(ui_Container9, 22);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label9, 50);
    lv_obj_set_height(ui_Label9, lv_pct(100));
    lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label9, "FR1:");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempFR1 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_TempFR1, 50);
    lv_obj_set_height(ui_TempFR1, lv_pct(100));
    lv_obj_set_x(ui_TempFR1, 9);
    lv_obj_set_y(ui_TempFR1, 8);
    lv_obj_set_align(ui_TempFR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempFR1, "24°C");
    lv_obj_set_style_text_align(ui_TempFR1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempFR1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempFR1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempFR1, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempFR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempFR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempFR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempFR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempFR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_ContainerServoInfoRight);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_height(ui_Container10, 22);
    lv_obj_set_width(ui_Container10, lv_pct(100));
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label10, 50);
    lv_obj_set_height(ui_Label10, lv_pct(100));
    lv_obj_set_align(ui_Label10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label10, "FR2:");
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempFR2 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_TempFR2, 50);
    lv_obj_set_height(ui_TempFR2, lv_pct(100));
    lv_obj_set_x(ui_TempFR2, 9);
    lv_obj_set_y(ui_TempFR2, 8);
    lv_obj_set_align(ui_TempFR2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempFR2, "48°C");
    lv_obj_set_style_text_align(ui_TempFR2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempFR2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempFR2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempFR2, lv_color_hex(0xF30202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempFR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempFR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempFR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempFR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempFR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_ContainerServoInfoRight);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_height(ui_Container11, 22);
    lv_obj_set_width(ui_Container11, lv_pct(100));
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label11, 50);
    lv_obj_set_height(ui_Label11, lv_pct(100));
    lv_obj_set_align(ui_Label11, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label11, "FR3:");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempFR3 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_TempFR3, 50);
    lv_obj_set_height(ui_TempFR3, lv_pct(100));
    lv_obj_set_x(ui_TempFR3, 9);
    lv_obj_set_y(ui_TempFR3, 8);
    lv_obj_set_align(ui_TempFR3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempFR3, "37°C");
    lv_obj_set_style_text_align(ui_TempFR3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempFR3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempFR3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempFR3, lv_color_hex(0xF19100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempFR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempFR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempFR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempFR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempFR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_ContainerServoInfoRight);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_height(ui_Container12, 22);
    lv_obj_set_width(ui_Container12, lv_pct(100));
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label12, 50);
    lv_obj_set_height(ui_Label12, lv_pct(100));
    lv_obj_set_align(ui_Label12, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label12, "BR1:");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBR1 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_TempBR1, 50);
    lv_obj_set_height(ui_TempBR1, lv_pct(100));
    lv_obj_set_x(ui_TempBR1, 9);
    lv_obj_set_y(ui_TempBR1, 8);
    lv_obj_set_align(ui_TempBR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempBR1, "24°C");
    lv_obj_set_style_text_align(ui_TempBR1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempBR1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempBR1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempBR1, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempBR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempBR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempBR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempBR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_ContainerServoInfoRight);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_height(ui_Container13, 22);
    lv_obj_set_width(ui_Container13, lv_pct(100));
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label13, 50);
    lv_obj_set_height(ui_Label13, lv_pct(100));
    lv_obj_set_align(ui_Label13, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label13, "BR2:");
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBR2 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_TempBR2, 50);
    lv_obj_set_height(ui_TempBR2, lv_pct(100));
    lv_obj_set_x(ui_TempBR2, 9);
    lv_obj_set_y(ui_TempBR2, 8);
    lv_obj_set_align(ui_TempBR2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempBR2, "24°C");
    lv_obj_set_style_text_align(ui_TempBR2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempBR2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempBR2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempBR2, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempBR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempBR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempBR2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempBR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_ContainerServoInfoRight);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_height(ui_Container14, 22);
    lv_obj_set_width(ui_Container14, lv_pct(100));
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label14, 50);
    lv_obj_set_height(ui_Label14, lv_pct(100));
    lv_obj_set_align(ui_Label14, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label14, "BR3:");
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBR3 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_TempBR3, 50);
    lv_obj_set_height(ui_TempBR3, lv_pct(100));
    lv_obj_set_x(ui_TempBR3, 9);
    lv_obj_set_y(ui_TempBR3, 8);
    lv_obj_set_align(ui_TempBR3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempBR3, "24°C");
    lv_obj_set_style_text_align(ui_TempBR3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempBR3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TempBR3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempBR3, lv_color_hex(0x05B017), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempBR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempBR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempBR3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempBR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_ContainerServoInfoLeft = NULL;
    ui_Container3 = NULL;
    ui_Label3 = NULL;
    ui_TempFL1 = NULL;
    ui_Container4 = NULL;
    ui_Label4 = NULL;
    ui_TempFL2 = NULL;
    ui_Container5 = NULL;
    ui_Label5 = NULL;
    ui_TempFL3 = NULL;
    ui_Container6 = NULL;
    ui_Label6 = NULL;
    ui_TempBL1 = NULL;
    ui_Container7 = NULL;
    ui_Label7 = NULL;
    ui_TempBL2 = NULL;
    ui_Container8 = NULL;
    ui_Label8 = NULL;
    ui_TempBL3 = NULL;
    ui_ContainerServoInfoRight = NULL;
    ui_Container9 = NULL;
    ui_Label9 = NULL;
    ui_TempFR1 = NULL;
    ui_Container10 = NULL;
    ui_Label10 = NULL;
    ui_TempFR2 = NULL;
    ui_Container11 = NULL;
    ui_Label11 = NULL;
    ui_TempFR3 = NULL;
    ui_Container12 = NULL;
    ui_Label12 = NULL;
    ui_TempBR1 = NULL;
    ui_Container13 = NULL;
    ui_Label13 = NULL;
    ui_TempBR2 = NULL;
    ui_Container14 = NULL;
    ui_Label14 = NULL;
    ui_TempBR3 = NULL;

}
