// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32S3-Touch-AMOLED-1.64-Robot_SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_ServoLabelsLeft;
extern lv_obj_t * ui_CalibrateButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_ServoLabelsRight;
extern lv_obj_t * ui_ContainerCalbrationLeft;
extern lv_obj_t * ui_BarFL1;
extern lv_obj_t * ui_BarFL2;
extern lv_obj_t * ui_BarFL3;
extern lv_obj_t * ui_BarBL1;
extern lv_obj_t * ui_BarBL2;
extern lv_obj_t * ui_BarBL3;
extern lv_obj_t * ui_ContainerCalbrationRight;
extern lv_obj_t * ui_BarFR1;
extern lv_obj_t * ui_BarFR2;
extern lv_obj_t * ui_BarFR3;
extern lv_obj_t * ui_BarBR1;
extern lv_obj_t * ui_BarBR2;
extern lv_obj_t * ui_BarBR3;
extern lv_obj_t * ui_WiggleButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_CalibrationInfo;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CalibrateButton;
extern lv_obj_t * uic_BarFL1;
extern lv_obj_t * uic_BarFL2;
extern lv_obj_t * uic_BarFL3;
extern lv_obj_t * uic_BarBL1;
extern lv_obj_t * uic_BarBL2;
extern lv_obj_t * uic_BarBL3;
extern lv_obj_t * uic_BarFR1;
extern lv_obj_t * uic_BarFR2;
extern lv_obj_t * uic_BarFR3;
extern lv_obj_t * uic_BarBR1;
extern lv_obj_t * uic_BarBR2;
extern lv_obj_t * uic_BarBR3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

